# Author: Aniruddha Gokhale
# Vanderbilt University
# Created May 2017,
# Modified Nov 2017
# Modified Oct 2018
# Modified Oct 2019 to use Python3
# Modified Nov 2022 - Vikash Singh
# Run this docker file with --no-cache --network=host options in docker build
#
# For Cloud Computing class
#
# First, use the latest ubuntu image, which points to the
# latest LTS image, currently 20.04
FROM ubuntu:focal
#
# Now install the needed python packages
RUN apt-get -y update && apt-get install -y net-tools python3 gcc
RUN apt-get install -y python3-dev python3-pip
RUN python3 -m pip install --upgrade pip
RUN pip3 install --upgrade numpy
#
# Next, copy our matrix inverse code into the container
COPY *.py /
#
# Run a command shell (for Swarm, we comment this out)
CMD /bin/bash